#!/bin/bash

# Performance Regression Detection Script
# Fails build if performance degrades by more than 20% compared to baseline
# Generated by Claude Code

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Default values
THRESHOLD=20.0
BASELINE_FILE="test/perf/baselines.json"
RESULTS_FILE="test_results/perf_test_raw.json"
VERBOSE=false

# Print usage
usage() {
    echo "Usage: check_performance_regression.sh [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -t, --threshold PERCENT     Degradation threshold percentage (default: 20.0)"
    echo "  -b, --baseline FILE         Path to baseline JSON file (default: test/perf/baselines.json)"
    echo "  -r, --results FILE          Path to test results JSON file (default: test_results/perf_test_raw.json)"
    echo "  -v, --verbose               Enable verbose output"
    echo "  -h, --help                  Show this help message"
    echo ""
    echo "Exit codes:"
    echo "  0 - No regression detected"
    echo "  1 - Regression detected or error occurred"
    echo ""
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -t|--threshold)
            THRESHOLD="$2"
            shift 2
            ;;
        -b|--baseline)
            BASELINE_FILE="$2"
            shift 2
            ;;
        -r|--results)
            RESULTS_FILE="$2"
            shift 2
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo -e "${RED}Error: Unknown option: $1${NC}"
            usage
            exit 1
            ;;
    esac
done

# Validate jq is available
if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq is required but not installed${NC}"
    echo "Install jq: brew install jq (macOS) or apt-get install jq (Linux)"
    exit 1
fi

# Check if results file exists
if [ ! -f "$RESULTS_FILE" ]; then
    echo -e "${RED}Error: Results file not found: $RESULTS_FILE${NC}"
    exit 1
fi

# Check if baseline file exists
if [ ! -f "$BASELINE_FILE" ]; then
    echo -e "${YELLOW}Warning: Baseline file not found: $BASELINE_FILE${NC}"
    echo "This appears to be a baseline run. No regression check will be performed."
    exit 0
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Performance Regression Detection${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Baseline: $BASELINE_FILE"
echo "Results:  $RESULTS_FILE"
echo "Threshold: ${THRESHOLD}% degradation"
echo ""

# Counters
REGRESSION_COUNT=0
IMPROVEMENT_COUNT=0
STABLE_COUNT=0

# Extract metrics from test results
# Flutter test JSON format: result array with testID, status, time, etc.
extract_metric_name() {
    local test_id="$1"
    # Convert test ID to metric name (e.g., "app launch time must be under 2000ms" -> "app launch time")
    echo "$test_id" | sed 's/ must be under.*ms//' | sed 's/ average.*//' | sed 's/ (.*runs)//' | sed 's/_perf_test//' | tr '_' ' '
}

# Process baseline comparisons
process_regression_check() {
    local metric_name="$1"
    local current_value="$2"
    local baseline_value="$3"

    # Skip if baseline value is 0 or negative
    if [ -z "$baseline_value" ] || [ "$baseline_value" -le 0 ]; then
        return
    fi

    # Calculate percentage change
    local difference=$((current_value - baseline_value))
    local percent_change=$(echo "scale=2; ($difference / $baseline_value) * 100" | bc)

    # Determine if regression or improvement
    local is_regression=false
    local is_improvement=false

    if (( $(echo "$percent_change > $THRESHOLD" | bc -l) )); then
        is_regression=true
    elif (( $(echo "$percent_change < -$THRESHOLD" | bc -l) )); then
        is_improvement=true
    fi

    # Output result
    if [ "$is_regression" = true ]; then
        echo -e "  ${RED}⚠️  REGRESSION${NC}"
        echo "     Metric: $metric_name"
        echo "     Baseline: ${baseline_value}ms"
        echo "     Current:  ${current_value}ms"
        echo "     Change:   +${difference}ms (+${percent_change}%)"
        echo ""
        REGRESSION_COUNT=$((REGRESSION_COUNT + 1))
    elif [ "$is_improvement" = true ]; then
        if [ "$VERBOSE" = true ]; then
            echo -e "  ${GREEN}✓ IMPROVEMENT${NC}"
            echo "     Metric: $metric_name"
            echo "     Baseline: ${baseline_value}ms"
            echo "     Current:  ${current_value}ms"
            echo "     Change:   ${difference}ms (${percent_change}%)"
            echo ""
        fi
        IMPROVEMENT_COUNT=$((IMPROVEMENT_COUNT + 1))
    else
        if [ "$VERBOSE" = true ]; then
            echo -e "  ${GREEN}✓ STABLE${NC}"
            echo "     Metric: $metric_name"
            echo "     Baseline: ${baseline_value}ms"
            echo "     Current:  ${current_value}ms"
            echo "     Change:   ${difference}ms (${percent_change}%)"
            echo ""
        fi
        STABLE_COUNT=$((STABLE_COUNT + 1))
    fi
}

# Read baseline file
BASELINE_METRICS=$(jq -r '.baselines // {} | keys[]' "$BASELINE_FILE" 2>/dev/null || echo "")

if [ -z "$BASELINE_METRICS" ]; then
    echo -e "${YELLOW}Warning: No metrics found in baseline file${NC}"
    exit 0
fi

# Extract test results and compare with baseline
echo -e "${BLUE}Comparing metrics against baseline...${NC}"
echo ""

# Parse test results JSON
# Format: {"result": [{"testID": "...", "time": 1234, ...}, ...]}

for metric_key in $BASELINE_METRICS; do
    baseline_value=$(jq -r ".baselines.\"$metric_key\".value_ms // .baselines.\"$metric_key\".value // empty" "$BASELINE_FILE")

    if [ -z "$baseline_value" ]; then
        continue
    fi

    # Try to find corresponding test result
    # Match by test name patterns
    metric_display=$(echo "$metric_key" | tr '_' ' ')

    # Extract time from test results
    # Try different patterns: exact match, contains, etc.
    current_value=$(jq -r "
        .result[] |
        select(.testID | contains(\"$(echo "$metric_key" | sed 's/_/ /g')\")) |
        .time // .duration // empty
    " "$RESULTS_FILE" | head -1)

    # If no match found, try alternative patterns
    if [ -z "$current_value" ]; then
        current_value=$(jq -r "
            .result[] |
            select(.testID | contains(\"$(echo "$metric_key" | cut -d'_' -f1-2 | tr '_' ' ')\")) |
            .time // .duration // empty
        " "$RESULTS_FILE" | head -1)
    fi

    # If we found a matching value, compare
    if [ -n "$current_value" ] && [ "$current_value" != "null" ]; then
        process_regression_check "$metric_display" "$current_value" "$baseline_value"
    elif [ "$VERBOSE" = true ]; then
        echo -e "  ${YELLOW}⊘ SKIPPED${NC}"
        echo "     Metric: $metric_display"
        echo "     Reason: No matching test result found"
        echo ""
    fi
done

# Print summary
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Summary${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Regressions:  $REGRESSION_COUNT"
echo "Improvements: $IMPROVEMENT_COUNT"
echo "Stable:       $STABLE_COUNT"
echo ""

# Exit with error if regression detected
if [ $REGRESSION_COUNT -gt 0 ]; then
    echo -e "${RED}❌ PERFORMANCE REGRESSION DETECTED${NC}"
    echo -e "${RED}Build failed due to $REGRESSION_COUNT regression(s) exceeding ${THRESHOLD}% threshold${NC}"
    echo ""
    echo "To update baselines after investigating:"
    echo "  1. Review the performance changes"
    echo "  2. If acceptable, update: $BASELINE_FILE"
    echo ""
    exit 1
else
    echo -e "${GREEN}✅ No performance regression detected${NC}"
    echo ""
    exit 0
fi
